language: android
jdk: oraclejdk7
env:
  matrix:
    #- ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
     - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-21.1.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
    - platform-tools
  licenses:
    - android-sdk-license-.+
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator